# Generated by Django 5.2.8 on 2025-11-29 17:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_accounttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Consignacion'), ('WITHDRAW', 'Retiro'), ('TRANSFER', 'Transferencia')], max_length=15, verbose_name='Transaction Type')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Balance After')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.account')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfer', to='account.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
