# Generated by Django 5.2.8 on 2025-11-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('0', 'Consignacion'), ('1', 'Retiro'), ('2', 'Transferencia')], max_length=15, verbose_name='Transaction Type'),
        ),
    ]
