# Generated by Django 5.2.8 on 2025-11-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Consignacion'), ('WITHDRAW', 'Retiro'), ('TRANSFER', 'Transferencia')], max_length=15, verbose_name='Transaction Type'),
        ),
    ]
