# Generated by Django 5.2.8 on 2025-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['id'], 'verbose_name': 'Account_Type', 'verbose_name_plural': 'Account_Types'},
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
